from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('terms/mentor/', views.mentor_terms, name='mentor_terms'),
    path('terms/participant/', views.participant_terms, name='participant_terms'),
    path('participant/dashboard/', views.participant_dashboard, name='participant_dashboard'),
    path('mentor/dashboard/', views.mentor_dashboard, name='mentor_dashboard'),
    path('participant/profile/', views.participant_profile, name='participant_profile'),
    path('mentor/profile/', views.mentor_profile, name='mentor_profile'),
    path('submit-feedback/<int:mentor_id>/', views.submit_feedback, name='submit_feedback'),
    path('learning-resources/', views.learning_resources, name='learning_resources'),
    path('mlearning-resources/', views.mlearning_resources, name='mlearning_resources'),
    path('upload-resource/', views.upload_resource, name='upload_resource'),
    path('rate-resource/<int:resource_id>/', views.rate_resource, name='rate_resource'),
    path('submit-mentorship-request/', views.submit_mentorship_request, name='submit_mentorship_request'),
    path('schedule-session/<int:request_id>/', views.schedule_session, name='schedule_session'),
    path('chat-with-mentor/<int:request_id>/', views.chat_with_mentor, name='chat_with_mentor'),
    path('manage-mentorship-requests/', views.manage_mentorship_requests, name='manage_mentorship_requests'),
    path('approve-mentorship-request/<int:request_id>/', views.approve_mentorship_request, name='approve_mentorship_request'),
    path('decline-mentorship-request/<int:request_id>/', views.decline_mentorship_request, name='decline_mentorship_request'),
    path('chat-with-mentee/<int:request_id>/', views.chat_with_mentee, name='chat_with_mentee'),
    path('manage-schedule/', views.manage_schedule, name='manage_schedule'),
    path('job-listings/', views.job_listings, name='job_listings'),
    path('save-job/<int:job_id>/', views.save_job, name='save_job'),
    path('apply-for-job/<int:job_id>/', views.apply_for_job, name='apply_for_job'),
    path('job-application-tracker/', views.job_application_tracker, name='job_application_tracker'),
    path('employer-dashboard/', views.employer_dashboard, name='employer_dashboard'),
    path('manage-applicants/<int:job_id>/', views.manage_applicants, name='manage_applicants'),
    path('update-application-status/<int:application_id>/<str:status>/', views.update_application_status, name='update_application_status'),
    path('mark-notification-seen/<int:notification_id>/', views.mark_notification_seen, name='mark_notification_seen'),
    path('add-to-google-calendar/<int:session_id>/', views.add_to_google_calendar, name='add_to_google_calendar'),
    path('upvote-message/<int:message_id>/', views.upvote_message, name='upvote_message'),
    path('downvote-message/<int:message_id>/', views.downvote_message, name='downvote_message'),
    path('google/callback/', views.google_callback, name='google_callback'),
    path('thread/<int:thread_id>/', views.thread_detail, name='thread_detail'),
    path('mentorthread/<int:thread_id>/', views.mentorthread_detail, name='mentorthread_detail'),
    path('create_thread/', views.create_thread, name='create_thread'),
    path('mcreate_thread/', views.mcreate_thread, name='mcreate_thread'),
    path('reply/<int:thread_id>/', views.reply_to_thread, name='reply_to_thread'),
    path('vote/<int:comment_id>/<str:vote_type>/', views.vote_comment, name='vote_comment'),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('mvote/<int:comment_id>/<str:vote_type>/', views.mvote_comment, name='mvote_comment'),
    path('mdelete_comment/<int:comment_id>/', views.mdelete_comment, name='mdelete_comment'),
    path('threads/', views.list_threads, name='list_threads'),
    path('mentorthreads/', views.mentorlist_threads, name='mentorlist_threads'),
    path('thread/<int:thread_id>/vote/<str:action>/', views.vote_thread, name='vote_thread'),
    path('mthread/<int:thread_id>/vote/<str:action>/', views.mvote_thread, name='mvote_thread'),
    path('delete_thread/<int:id>/', views.delete_thread, name='delete_thread'),
    path('mdelete_thread/<int:id>/', views.mdelete_thread, name='mdelete_thread'),
    path('account/settings/', views.account_settings, name='account_settings'),
    path('maccount/settings/', views.maccount_settings, name='maccount_settings'),
    path('account/change_email/', views.change_email, name='change_email'),
    path('account/change_password/', views.change_password, name='change_password'),
    path('account/delete_account/', views.delete_account, name='delete_account'),
     path('maccount/change_email/', views.mchange_email, name='mchange_email'),
    path('maccount/change_password/', views.mchange_password, name='mchange_password'),
    path('maccount/delete_account/', views.mdelete_account, name='mdelete_account'),
    path('', views.homepage, name='homepage'),
    path('about-us/', views.about_us, name='about_us'),
    path('features/', views.features, name='features'),
    path('mentor/job-listings/', views.mentor_job_listings, name='mentor_job_listings'),
    path('contact-us/', views.contact_us, name='contact_us'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)