from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('terms/mentor/', views.mentor_terms, name='mentor_terms'),
    path('terms/participant/', views.participant_terms, name='participant_terms'),
    path('participant/dashboard/', views.participant_dashboard, name='participant_dashboard'),
    path('mentor/dashboard/', views.mentor_dashboard, name='mentor_dashboard'),
    path('participant/profile/<int:participant_id>/', views.participant_profile, name='participant_profile'),
    path('mentor/profile/<int:mentor_id>', views.mentor_profile, name='mentor_profile'),
    path('submit-feedback/<int:mentor_id>/', views.submit_feedback, name='submit_feedback'),
    path('learning-resources/', views.learning_resources, name='learning_resources'),
    path('mlearning-resources/', views.mlearning_resources, name='mlearning_resources'),
    path('upload-resource/', views.upload_resource, name='upload_resource'),
    path('rate-resource/<int:resource_id>/', views.rate_resource, name='rate_resource'),
    path('submit-mentorship-request/', views.submit_mentorship_request, name='submit_mentorship_request'),
    path('chat-with-mentor/<int:request_id>/', views.chat_with_mentor, name='chat_with_mentor'),
    path('manage-mentorship-requests/', views.manage_mentorship_requests, name='manage_mentorship_requests'),
    path('approve-mentorship-request/<int:request_id>/', views.approve_mentorship_request, name='approve_mentorship_request'),
    path('decline-mentorship-request/<int:request_id>/', views.decline_mentorship_request, name='decline_mentorship_request'),
    path('chat-with-mentee/<int:request_id>/', views.chat_with_mentee, name='chat_with_mentee'),
    path('manage-schedule/', views.manage_schedule, name='manage_schedule'),
    path('job-listings/', views.job_listings, name='job_listings'),
    path('save-job/<int:job_id>/', views.save_job, name='save_job'),
    path('apply-for-job/<int:job_id>/', views.apply_for_job, name='apply_for_job'),
    path('job-application-tracker/', views.job_application_tracker, name='job_application_tracker'),
    path('manage-applicants/<int:job_id>/', views.manage_applicants, name='manage_applicants'),
    path('update-application-status/<int:application_id>/<str:status>/', views.update_application_status, name='update_application_status'),
    path('mark-notification-seen/<int:notification_id>/', views.mark_notification_seen, name='mark_notification_seen'),
    path('upvote-message/<int:message_id>/', views.upvote_message, name='upvote_message'),
    path('downvote-message/<int:message_id>/', views.downvote_message, name='downvote_message'),
    path('google/callback/', views.google_callback, name='google_callback'),
    path('thread/<int:thread_id>/', views.thread_detail, name='thread_detail'),
    path('mentorthread/<int:thread_id>/', views.mentorthread_detail, name='mentorthread_detail'),
    path('create_thread/', views.create_thread, name='create_thread'),
    path('mcreate_thread/', views.mcreate_thread, name='mcreate_thread'),
    path('reply/<int:thread_id>/', views.reply_to_thread, name='reply_to_thread'),
    path('vote/<int:comment_id>/<str:vote_type>/', views.vote_comment, name='vote_comment'),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('mvote/<int:comment_id>/<str:vote_type>/', views.mvote_comment, name='mvote_comment'),
    path('mdelete_comment/<int:comment_id>/', views.mdelete_comment, name='mdelete_comment'),
    path('threads/', views.list_threads, name='list_threads'),
    path('mentorthreads/', views.mentorlist_threads, name='mentorlist_threads'),
    path('thread/<int:thread_id>/vote/<str:action>/', views.vote_thread, name='vote_thread'),
    path('mthread/<int:thread_id>/vote/<str:action>/', views.mvote_thread, name='mvote_thread'),
    path('delete_thread/<int:id>/', views.delete_thread, name='delete_thread'),
    path('mdelete_thread/<int:id>/', views.mdelete_thread, name='mdelete_thread'),
    path('account/settings/', views.account_settings, name='account_settings'),
    path('maccount/settings/', views.maccount_settings, name='maccount_settings'),
    path('account/change_email/', views.change_email, name='change_email'),
    path('account/change_password/', views.change_password, name='change_password'),
    path('account/delete_account/', views.delete_account, name='delete_account'),
     path('maccount/change_email/', views.mchange_email, name='mchange_email'),
    path('maccount/change_password/', views.mchange_password, name='mchange_password'),
    path('maccount/delete_account/', views.mdelete_account, name='mdelete_account'),
    path('', views.homepage, name='homepage'),
    path('about-us/', views.about_us, name='about_us'),
    path('features/', views.features, name='features'),
    path('mentor/job-listings/', views.mentor_job_listings, name='mentor_job_listings'),
    path('contact-us/', views.contact_us, name='contact_us'),
    path('mentor/rate/<int:mentor_id>/', views.rate_mentor, name='rate_mentor'),
    path('notification-seen/<int:notification_id>/<int:job_id>/', views.notification_seen, name='notification_seen'),
     path('delete-job/<int:job_id>/', views.delete_job_listing, name='delete_job_listing'),
    path('resources/delete/<int:resource_id>/', views.delete_learning_resource, name='delete_learning_resource'),
    path("issue-certificate/", views.issue_certificate, name="issue_certificate"),
    path('delete-certificate/<int:certificate_id>/', views.delete_certificate, name='delete_certificate'),
    path('enroll/<int:resource_id>/', views.enroll_course, name='enroll_course'),
    path('menroll/<int:resource_id>/', views.menroll_course, name='menroll_course'),
    path('course/<int:resource_id>/', views.course_detail, name='course_detail'),
    path('mcourse/<int:resource_id>/', views.mcourse_detail, name='mcourse_detail'),
    path('chapter/<int:chapter_id>/done/', views.mark_chapter_done, name='mark_chapter_done'),
    path('quiz/<int:quiz_id>/', views.take_quiz, name='take_quiz'),
    path("final-quiz/<int:quiz_id>/", views.take_final_quiz, name="take_final_quiz"),
    path('upload-chapter-quiz/', views.upload_chapter_quiz, name='upload_chapter_quiz'),
    path('upload-final-quiz/', views.upload_final_quiz, name='upload_final_quiz'),
    path('quiz/<int:quiz_id>/reset/', views.reset_quiz, name='reset_quiz'),
    path('final-quiz/<int:quiz_id>/reset/', views.reset_final_quiz, name='reset_final_quiz'),
    path('generate-certificate/<int:resource_id>/', views.generate_certificate, name='generate_certificate'),
    path('participant/mentors/<int:mentor_id>/availability/', views.view_mentor_availability, name='view_mentor_availability'),
    path('participant/notifications/mark-seen/<int:notification_id>/', views.mark_notification_seen, name='mark_notification_seen'),
    path('mentor/availability/', views.mentor_add_availability, name='mentor_add_availability'),
    path('mentor/sessions/', views.mentor_sessions, name='mentor_sessions'),
    path('mentor/sessions/confirm/<int:session_id>/', views.confirm_session, name='confirm_session'),
    path('notification/seen/<int:notification_id>/', views.mark_notification_seen, name='mark_notification_seen'),
    path('pnotification/seen/<int:notification_id>/', views.pmark_notification_seen, name='pmark_notification_seen'),
    path('api/quiz/<int:quiz_id>/', views.get_quiz, name='get_quiz'),
    path('api/quiz/<int:quiz_id>/submit/', views.submit_quiz_attempt, name='submit_quiz_attempt'),
    path('ad/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('ad/resource/<int:resource_id>/progress/', views.resource_participant_progress, name='resource_participant_progress'),
    path('ad/delete/user/<int:user_id>/', views.admin_delete_user, name='admin_delete_user'),
    path('ad/delete/resource/<int:resource_id>/', views.admin_delete_resource, name='admin_delete_resource'),
    path('ad/delete/thread/<int:thread_id>/', views.admin_delete_thread, name='admin_delete_thread'),
    path('ad/delete/job/<int:job_id>/', views.admin_delete_job, name='admin_delete_job'),
    path('ad/delete/slot/<int:slot_id>/', views.admin_delete_slot, name='admin_delete_slot'),
    path('ad/resource/<int:resource_id>/progress/', views.admin_view_resource_progress, name='admin_view_resource_progress'),
    path('ad/thread/<int:thread_id>/', views.admin_view_thread, name='admin_view_thread'),
    path("ad/comment/<int:comment_id>/delete/", views.admin_delete_comment, name="admin_delete_comment"),
    path("ad/resource/<int:resource_id>/", views.admin_resource_detail, name="admin_resource_detail"),
    path("ad/job/<int:job_id>/", views.admin_job_detail, name="admin_job_detail"),
    path("ad/session/<int:session_id>/", views.admin_scheduled_session_detail, name="admin_scheduled_session_detail"),
    path("ad/chapter/delete/<int:chapter_id>/", views.admin_delete_chapter, name="admin_delete_chapter"),
    path("ad/feedback/delete/<int:feedback_id>/", views.admin_delete_feedback, name="admin_delete_feedback"),
    path("ad/user/<int:user_id>/", views.admin_view_user_profile, name="admin_view_user_profile"),
    path("ad/quiz/<int:quiz_id>/", views.admin_view_final_quiz, name="admin_view_final_quiz"),
    path("ad/quiz/<int:quiz_id>/delete/", views.admin_delete_final_quiz, name="admin_delete_final_quiz"),
    path('ad/resources/', views.admin_resources, name='admin_resources'),
    path('ad/threads/', views.admin_threads, name='admin_threads'),
    path('ad/jobs/', views.admin_jobs, name='admin_jobs'),
    path('ad/mentorship-requests/', views.admin_mentorship_requests, name='admin_mentorship_requests'),
    path('ad/job-applications/', views.admin_job_applications, name='admin_job_applications'),
    path('ad/mentor-availability/', views.admin_availability, name='admin_availability'),
    path('ad/scheduled-sessions/', views.admin_scheduled_sessions, name='admin_scheduled_sessions'),
    path('ad/feedbacks/', views.admin_feedbacks, name='admin_feedbacks'),
    path("ad/scheduled-sessions/delete/<int:session_id>/", views.admin_delete_scheduled_session, name="admin_delete_scheduled_session"),
    path("ad/mentorship-requests/delete/<int:request_id>/", views.admin_delete_mentorship_request, name="admin_delete_mentorship_request"),
    path("ad/resource/progress/<int:resource_id>/", views.admin_view_resource_progress, name="admin_view_resource_progress"),
    path('participant/<int:participant_id>/edit/', views.edit_participant_profile, name='edit_participant_profile'),
    path('mentor/<int:mentor_id>/edit/', views.edit_mentor_profile, name='edit_mentor_profile'),
    path('participant/schedule/', views.available_sessions, name='available_sessions'),
    path('schedule_session/<int:mentor_id>/<int:session_id>/', views.schedule_session, name='schedule_session'),
    path('upload-ai-chapter-quiz/', views.upload_ai_chapter_quiz, name='upload_chapter_ai_quiz'),
    path('upload-ai-final-quiz/', views.upload_final_ai_quiz, name='upload_final_ai_quiz'),
    path('api/ai-generate-chapter-quiz/<int:chapter_id>/', views.ai_generate_chapter_quiz, name='ai_generate_chapter_quiz'),
    path('api/ai-generate-final-quiz/<int:resource_id>/', views.ai_generate_final_quiz, name='ai_generate_final_quiz'),
    path('mentor/profile-settings/', views.mentor_profile_settings, name='mentor_profile_settings'),
    path('participant/profile-settings/', views.participant_profile_settings, name='participant_profile_settings'),
    path("set-language/", views.set_language_preference, name="set_language_preference"),


    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

