# Generated by Django 5.1.5 on 2025-02-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshiprequest',
            name='mentor_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
