# Generated by Django 5.1.5 on 2025-02-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_resource_final_quiz_alter_quiz_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='quiz_attempts',
            field=models.JSONField(default=dict),
        ),
    ]
