# Generated by Django 5.1.5 on 2025-02-18 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_userprogress_quiz_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='participant',
        ),
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone.resource'),
        ),
    ]
