# Generated by Django 5.1.5 on 2025-02-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_thread_comment_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
