# Generated by Django 5.1.5 on 2025-02-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_thread_downvotes_thread_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(default='Cover letter not provided.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(default='', upload_to='resumes/'),
            preserve_default=False,
        ),
    ]
