# Generated by Django 5.1.5 on 2025-02-19 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_session_is_confirmed_mentoravailability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledsession',
            name='mentorship_request',
        ),
        migrations.AlterField(
            model_name='scheduledsession',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_availability', to=settings.AUTH_USER_MODEL),
        ),
    ]
