# Generated by Django 5.1.5 on 2025-02-06 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_jobapplication_cover_letter_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='job_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capstone.jobapplication'),
        ),
    ]
