# Generated by Django 5.1.5 on 2025-02-19 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_remove_scheduledsession_mentorship_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledsession',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
