# Generated by Django 5.1.5 on 2025-02-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0008_notification_job_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='accepted_by_mentor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
