# Generated by Django 5.1.5 on 2025-02-19 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0008_scheduledsession_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledsession',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledsession',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledsession',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_scheduled_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduledsession',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_scheduled_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
