# Generated by Django 5.1.5 on 2025-02-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0011_resource_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='difficulty',
        ),
        migrations.AlterField(
            model_name='resource',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_covers/'),
        ),
    ]
