# Generated by Django 5.1.5 on 2025-02-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_quiz_correct_answer_quiz_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='options',
        ),
        migrations.AlterField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('sw', 'Swahili'), ('rn', 'Rundi')], default='fr', max_length=2),
        ),
    ]
