# Generated by Django 5.1.5 on 2025-02-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_remove_quiz_options_alter_user_language_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('sw', 'Swahili'), ('run', 'Rundi')], default='fr', max_length=4),
        ),
    ]
