# Generated by Django 5.1.5 on 2025-02-21 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0012_remove_resource_difficulty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='question',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('SHORT_ANSWER', 'Short Answer'), ('DOCUMENT_UPLOAD', 'Document Upload')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='capstone.quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='resource',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('score', models.FloatField()),
                ('attempt_date', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='capstone.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
