# Generated by Django 5.1.5 on 2025-02-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0016_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledsession',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
