# Generated by Django 5.1.5 on 2025-02-13 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='final_quiz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_quiz', to='capstone.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='capstone.resource'),
        ),
    ]
