# Generated by Django 5.1.5 on 2025-02-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_resource_translated_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='correct_answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='options',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='translated_options',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='quiz',
            name='translated_text',
            field=models.JSONField(default=dict),
        ),
    ]
