# Generated by Django 5.1.5 on 2025-02-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_scheduledsession_is_confirmed_scheduledsession_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoravailability',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
