# Generated by Django 5.1.5 on 2025-02-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0010_mentoravailability_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='resource_covers/'),
        ),
    ]
