# Generated by Django 5.1.5 on 2025-02-21 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0014_quiz_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='certificate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='capstone.certificate'),
        ),
    ]
